Sosullga/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('sosull.urls')),
    path('admin/', admin.site.urls),
]

sosull/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name='index'),
    path("series/<int:series_id>", views.series, name='series'),
    path("login", views.login_view, name='login'),
    path("logout", views.logout_view, name='logout'),
    path("pageSetting", views.pageSetting, name='pageSetting'),
    path("setting", views.setting, name='setting'),
    path("account", views.account, name='account'),
    path("request", views.request, name='request'),
    path("register", views.register, name='register'),
    path("read/<int:read_id>/<int:read_page>", views.read, name='read'),
    path("read/<int:read_id>/next", views.next, name="next"),
    path("read/<int:read_id>/bookmark", views.bookmark, name="bookmark"),
]

sosull/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from dateutil.relativedelta import relativedelta

# Create your models here.
class Novel(models.Model):
    title = models.CharField(max_length=100)
    category = models.CharField(max_length=30, null=True, blank=True)
    file = models.FileField(upload_to='novel/', null=True, blank=True)
    rating = models.CharField(max_length=4, null=True, blank=True)

    def __str__(self):
        return f"{self.title}"

class Reader(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f"{self.user.username}"

class Setting(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    dark = models.BooleanField(default=False)
    size = models.CharField(max_length=10, default=16)
    height = models.CharField(max_length=10, default=24)
    width = models.CharField(max_length=10, default=48)

    def __str__(self):
        return f"{self.user}"

class Marker(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    novel = models.ForeignKey(Novel, on_delete=models.CASCADE, blank=True, null=True)
    page = models.IntegerField(default=1)
    percent = models.IntegerField(default=0)
    time = models.DateTimeField(default=datetime.now())

    def __str__(self):
        return f"{self.user} - {self.novel.title} - {self.page} ({self.percent}%)"

class Bookmark(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    novel = models.ForeignKey(Novel, on_delete=models.CASCADE, blank=True, null=True)
    page = models.IntegerField(default=1)
    time = models.DateTimeField(default=datetime.now())

    def __str__(self):
        return f"{self.user} - {self.novel.title} - {self.page}"

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="commenter_of", blank=True, null=True)
    novel = models.ForeignKey(Novel, on_delete=models.CASCADE, related_name='comment_of', blank=True, null=True)
    rating = models.IntegerField(blank=True, null=True)
    content = models.CharField(max_length=50000)
    time = models.DateTimeField(default=datetime.now())

    def __str__ (self):
        return f"{self.author}"


class Request(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    author = models.CharField(max_length=200, blank=True, null=True)
    solved = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user} - {self.title}"

sosull/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.db.models import Count, Avg
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.http import JsonResponse
from django.core import serializers
from datetime import datetime
import math
import json

# Create your views here
from .models import *

def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('login'))

    try:
        recent = Marker.objects.filter(user=request.user).all().latest('time')

        if request.method == 'POST':
            query = request.POST['search']

            print(query)

            result = Novel.objects.filter(title__contains=query)

            if result:
                context = {
                    "user": request.user,
                    "novels": Novel.objects.all(),
                    "recent": recent,
                    "recentNovel": Novel.objects.get(title=recent.novel),
                    "result": result,
                }
            else:
                context = {
                    "user": request.user,
                    "novels": Novel.objects.all(),
                    "recent": recent,
                    "recentNovel": Novel.objects.get(title=recent.novel),
                    "resultNone": "결과가 없습니다.",
                }

            return render(request, "sosull/index.html", context)
        else :
            context = {
                "user": request.user,
                "novels": Novel.objects.all(),
                "recent": recent,
                "recentNovel": Novel.objects.get(title=recent.novel),
            }
            return render(request, "sosull/index.html", context)
    except:
        if request.method == 'POST':
            query = request.POST['search']

            print(query)

            result = Novel.objects.filter(title__contains=query)

            if result:
                context = {
                    "user": request.user,
                    "novels": Novel.objects.all(),
                    "recent": None,
                    "recentNovel": None,
                    "result": result,
                }
            else:
                context = {
                    "user": request.user,
                    "novels": Novel.objects.all(),
                    "recent": None,
                    "recentNovel": None,
                    "resultNone": "결과가 없습니다.",
                }

            return render(request, "sosull/index.html", context)
        else :
            context = {
                "user": request.user,
                "novels": Novel.objects.all(),
                "recent": None,
                "recentNovel": None,
            }
            return render(request, "sosull/index.html", context)

def request(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('login'))

    if request.method == 'POST':
        title = request.POST['title']
        author = request.POST['author']

        new_request = Request(user=request.user, title=title, author=author)

        new_request.save()

        return HttpResponseRedirect(reverse('request'))

    quest = Request.objects.all()

    context = {
        'quest': quest,
    }

    return render(request, "sosull/request.html", context)

def series(request, series_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('login'))

    try:
        novel = Novel.objects.get(pk=series_id)
        try:
            novel.rating = round(Comment.objects.filter(novel=novel).all().aggregate(Avg('rating'))['rating__avg'], 1)
        except:
            novel.rating = "-"
        novel.save()
    except novel.DoesNotExist:
        raise Http404("Post does not exist")

    if request.method == 'POST':
        rating = request.POST['rating']
        content = request.POST['content']

        if (rating == ""):
            new_comment = Comment(author=request.user, novel=novel, content=content)
        else:
            new_comment = Comment(author=request.user, novel=novel, rating=rating, content=content)

        new_comment.save()
        return HttpResponseRedirect(reverse('series', kwargs={'series_id': series_id}))

    try:
        marker = Marker.objects.get(user=request.user, novel=novel)
    except:
        marker = Marker(user=request.user, novel=novel, time=datetime.now())
        marker.save()

    comment = Comment.objects.filter(novel=novel).all()

    context = {
        "novel": novel,
        "comment": comment,
        "marker": marker
    }
    return render(request, "sosull/series.html", context)

def account(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('login'))

    marker = Marker.objects.filter(user=request.user).order_by("-time").all()
    bookmark = Bookmark.objects.filter(user=request.user).order_by("-time").all()
    comment = Comment.objects.filter(author=request.user).order_by("-time").all()
    quest = Request.objects.filter(user=request.user).all()

    context = {
        'history': marker,
        'bookmark': bookmark,
        'comment': comment,
        'quest': quest,
    }
    return render(request, "sosull/account.html", context)

def setting(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('login'))

    try:
        setting = Setting.objects.get(user=request.user)
    except:
        setting = Setting(user=request.user)
        setting.save()

    if request.method == 'POST':
        if request.POST['dark'] == "on":
            dark = True
        else:
            dark = False
        size = request.POST['size']
        height = request.POST['height']
        width = request.POST['width']

        setting.dark = dark
        setting.size = size
        setting.height = height
        setting.width = width
        setting.save()
        return HttpResponseRedirect(reverse('setting'))

    context = {
        'setting': setting
    }

    return render(request, "sosull/setting.html", context)

def read(request, read_id, read_page):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('login'))

    try:
        novel = Novel.objects.get(pk=read_id)
        novel.file.path
    except:
        return HttpResponseRedirect(reverse('series', kwargs={'series_id': read_id}))

    content = ""

    linePerPage = 100

    try:
        with open(novel.file.path, encoding='utf-8') as f:
            count = sum(1 for _ in f)

        total = math.ceil(count/linePerPage)

        if read_page > total:
            return HttpResponseRedirect(reverse('series', kwargs={'series_id': read_id}))

        with open(novel.file.path, "r", encoding='utf-8') as file:
            for i, line in enumerate(file):
                if (i >= (read_page-1)*linePerPage) and (i < read_page*linePerPage):
                    content = content+line
    except:
        with open(novel.file.path, encoding='utf-16') as f:
            count = sum(1 for _ in f)

        total = math.ceil(count/linePerPage)

        if read_page > total:
            return HttpResponseRedirect(reverse('series', kwargs={'series_id': read_id}))

        with open(novel.file.path, "r", encoding='utf-16') as file:
            for i, line in enumerate(file):
                if (i >= (read_page-1)*linePerPage) and (i < read_page*linePerPage):
                    content = content+line

    percent = round((read_page*100)/total)

    try:
        marker = Marker.objects.get(user=request.user, novel=novel)
        marker.page = read_page
        marker.percent = percent
        marker.time = datetime.now()
        marker.save()
    except:
        marker = Marker(user=request.user, novel=novel, page=read_page, percent=percent)
        marker.save()

    try:
        setting = Setting.objects.get(user=request.user)
    except:
        setting = Setting(user=request.user)
        setting.save()

    context = {
        "novel": novel,
        "content": content,
        "total": total,
        "page": read_page,
        "setting": setting,
    }
    return render(request, "sosull/read.html", context)

def pageSetting(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('login'))

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        user = request.user
        dark = request.headers.get('dark')
        size = request.headers.get('size')
        height = request.headers.get('height')
        width = request.headers.get('width')

        try:
            setting = Setting.objects.get(user=user)
            setting.user = user
            setting.dark = dark
            setting.size = size
            setting.height = height
            setting.width = width
            setting.save()
        except:
            setting = Setting(user=user, dark=dark, size=size, height=height, width=width)
            setting.save()
        data = {
            'result': 'Success!'
        }
        return JsonResponse(data)

def bookmark(request, read_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('login'))

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        read_page = int(request.headers.get('page'))
        novel = Novel.objects.get(pk=read_id)

        try:
            bookmark = Bookmark.objects.get(user=request.user, novel=novel, page=int(request.headers.get('page')))
            bookmark.time = datetime.now()
            bookmark.save()
        except:
            bookmark = Bookmark(user=request.user, novel=novel, page=int(request.headers.get('page')))
            bookmark.save()

        data = {
            'result': 'Success!'
        }
        return JsonResponse(data)

sosull/templates/sosull/account.html
{% extends "sosull/base.html" %}
{% load static %}

{% block title %}
소설가 | 설정
{% endblock %}

{% block body %}
<nav class="navbar navbar-light bg-white">
    <a class="navbar-brand" href="{% url 'index' %}">sosullga</a>
    <div class="dropdown ml-auto my-1 my-md-3 mr-n2">
      <button class="btn account dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-circle fa-lg"></i></button>
      <div class="dropdown-menu dropdown-menu-right rounded-0" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="{% url 'account' %}">{{ request.user.username }}의 계정</a>
        <a class="dropdown-item" href="{% url 'setting' %}">설정</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{% url 'logout' %}">로그아웃</a>
      </div>
    </div>
</nav>
<nav class="navbar navbar-light bg-white pb-0">
    <div class="container px-2">
        <div class="row w-100 m-0" style="cursor: pointer;">
            <div class="col-6 active-tab d-flex" onclick="location.href='{% url 'index' %}'">
                <p class="mx-auto">소설</p>
            </div>
            <div class="col-6 d-flex" onclick="location.href='{% url 'request' %}'">
                <p class="mx-auto">요청</p>
            </div>
        </div>
    </div>
</nav>


<div class="container py-3 px-2">
    <div class="bg-white border mt-2">
        <div class="p-4 border-bottom">
            <h5 class="mb-0">{{ request.user }}의 계정</h5>
        </div>
        <div class="p-4 border-bottom">
            <h6 class="mb-3">내 작품 (최근 본 순)</h6>
            <div class="row">
                {% for novel in history %}
                    <div class="col-12 col-md-6 px-2 px-md-4 myNovel" onclick="location.href='{% url 'read' novel.novel.pk novel.page %}'">
                        <div class="d-flex border-top border-bottom py-3">
                            <img class="cover" src="{% with 'sosull/cover/'|add:novel.novel.title|add:'.jpg' as image_static %}{% static image_static %}{% endwith %}" alt="{{ novel.novel }}">
                            <div class="d-flex flex-column">
                                <h5 class="novel-title mb-1">{{ novel.novel }}</h5>
                                <p class="mb-0 text-secondary font-weight-light">{{ novel.page }} 페이지 ({{ novel.percent }}%)</p>
                                <p class="mb-0 text-secondary"><small>{{ novel.time }}</small></p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="p-4 border-bottom">
            <h6 class="mb-3">북마크</h6>
            <table class="table table-hover">
                <thead>
                    <tr>
                    <th class="d-none d-md-block" scope="col">시간</th>
                    <th scope="col">제목</th>
                    <th scope="col">페이지</th>
                    </tr>
                </thead>
                <tbody>
                    {% for novel in bookmark %}
                        <tr class="bookmark" onclick="location.href='{% url 'read' novel.novel.pk novel.page %}'">
                            <td class="d-none d-md-block">{{ novel.time.month }}/{{ novel.time.day }}/{{ novel.time.year }}</td>
                            <td>{{ novel.novel }}</td>
                            <td>{{ novel.page }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="p-4 border-bottom">
            <h6 class="mb-3">내가 남긴 댓글</h6>
            {% for c in comment %}
                <div class="d-flex flex-column border-top py-2 px-2 accountComment" onclick="location.href='{% url 'series' c.novel.pk %}'">
                    <p class="mb-1"><small>{{ c.time.month }}/{{ c.time.day }}/{{ c.time.year }}</small></p>
                    <h6 class="mb-1">{{ c.novel }} | <i class="fas fa-star"></i> {% if c.rating %}{{ c.rating }}{% else %}-{% endif %}</h6>

                    <p class="mb-0">{{ c.content }}</p>
                </div>
            {% endfor %}
        </div>
        <div class="p-4 border-bottom">
            <h6 class="mb-3">요청</h6>
            {% if quest %}
            <table class="table">
                <thead>
                    <tr>
                        <th class="font-weight-light" scope="col">이름</th>
                        <th class="font-weight-light" scope="col">제목</th>
                        <th class="font-weight-light" scope="col">작가</th>
                        <th class="font-weight-light" scope="col">해결</th>
                    </tr>
                    </thead>
                <tbody>
                    {% for q in quest %}
                        <tr>
                            <td>{{ q.user }}</td>
                            <td>{{ q.title }}</td>
                            <td>{{ q.author }}</td>
                            <td>{% if q.solved == True %}<i class="fas fa-check-circle text-success"></i>{% else %}<i class="fas fa-times-circle text-danger"></i>{% endif %}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
                <p class="mb-0">아직 요청이 없습니다.</p>
            {% endif %}
        </div>
    </div>
</div>

<nav class="navbar navbar-light mt-2">
    <div class="container">
        <p class="logo text-secondary">SOSULLGA</p>
    </div>
</nav>
{% endblock %}

sosull/templates/sosull/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
        <script src="{% static 'sosull/rating-input.min.js' %}"></script>
        <script src="https://kit.fontawesome.com/e2a6521029.js" crossorigin="anonymous"></script>
        <link rel="shortcut icon" type="image/png" href="{% static 'sosull/favicon.png' %}"/>

        <link rel="stylesheet" href="{% static 'sosull/styles.css' %}" />
        <title>{% block title %}{% endblock %}</title>
    </head>

    <body class="light">
        {% block body %}
        {% endblock %}
    </body>

</html>

sosull/templates/sosull/index.html
{% extends "sosull/base.html" %}
{% load static %}

{% block title %}
소설가 | Home
{% endblock %}

{% block body %}
<nav class="navbar navbar-light bg-white">
    <a class="navbar-brand" href="{% url 'index' %}">sosullga</a>
    <div class="dropdown ml-auto my-1 my-md-3 mr-n2">
      <button class="btn account dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-circle fa-lg"></i></button>
      <div class="dropdown-menu dropdown-menu-right rounded-0" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="{% url 'account' %}">{{ request.user.username }}의 계정</a>
        <a class="dropdown-item" href="{% url 'setting' %}">설정</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{% url 'logout' %}">로그아웃</a>
      </div>
    </div>
</nav>
<nav class="navbar navbar-light bg-white pb-0">
    <div class="container px-2">
        <div class="row w-100 m-0" style="cursor: pointer;">
            <div class="col-6 active-tab d-flex" onclick="location.href='{% url 'index' %}'">
                <p class="mx-auto">소설</p>
            </div>
            <div class="col-6 d-flex" onclick="location.href='{% url 'request' %}'">
                <p class="mx-auto">요청</p>
            </div>
        </div>
    </div>
</nav>
<div class="container py-2 px-2">
    {% if recent is not None %}
    <div class="card rounded-0" style="width: 100%;">
        <div class="card-header">
            최근에 본 소설
        </div>
        <div class="card-body p-2 p-md-4">
            <img class="cover float-left" src="{% with 'sosull/cover/'|add:recentNovel.title|add:'.jpg' as image_static %}{% static image_static %}{% endwith %}" alt="{{ recentNovel.title }}">
            <div class="d-flex flex-column novel-card">
                <p class="novel-title mb-0 mb-md-1" onclick="location.href='{% url 'series' recentNovel.pk %}'" style="cursor: pointer;">{{ recentNovel.title }}</p>
                <p class="mb-2">{{ recentNovel.category }} | <i class="fas fa-star"></i> {{ recentNovel.rating }}</p>
                <div class="d-none d-md-flex">
                    <button type="button" class="btn btn-outline-secondary rounded-0 mr-1" onclick="location.href='{% url 'read' recentNovel.pk recent.page %}'">이어보기</button>
                    <button type="button" class="btn btn-info rounded-0" onclick="location.href='{% url 'read' recentNovel.pk 1 %}'">첫편보기</button>
                </div>
                <div class="d-flex d-md-none">
                    <button type="button" class="btn btn-sm btn-outline-secondary rounded-0 mr-1" onclick="location.href='{% url 'read' recentNovel.pk recent.page %}'">이어보기</button>
                    <button type="button" class="btn btn-sm btn-info rounded-0" onclick="location.href='{% url 'read' recentNovel.pk 1 %}'">첫편보기</button>
                </div>
                <p class="my-2">페이지 {{ recent.page }} ({{ recent.percent }}%)</p>
                <div class="w-100 mt-auto">
                    <div class="progress" style="height: 5px;">
                          <div class="progress-bar bg-info" role="progressbar" style="width: {{ recent.percent }}%;" aria-valuenow="{{ recent.percent }}" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

    <div class="bg-white border mt-2 py-3 px-2">
        <form class="p-4 d-flex w-100" action="{% url 'index' %}" method="post">
            {% csrf_token %}
            <input type="text" class="mb-0 search w-100" name="search" id="search" placeholder="검색하기" required>
            <button type="submit" class="btn btn-outline-info rounded-0 mb-0 ml-3"><i class="fas fa-search"></i></button>
        </form>
        {% if resultNone %}
        <div class="p-4">
            <h5 class="mb-3">결과</h5>
            <p class="mb-0">{{ resultNone }}</p>
        </div>
        {% endif %}
        {% if result %}
        <div class="p-4">
            <h5 class="mb-3">결과</h5>
            <table class="table table-hover">
                <tbody>
                    {% for r in result %}
                        <tr style="cursor: pointer;" onclick="location.href='{% url 'series' r.pk %}'">
                            <td>{{ r.title }}</td>
                            <td>{{ r.category }}</td>
                            <td><i class="fas fa-star"></i> {% if r.rating %}{{ r.rating }}{% else %}-{% endif %}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
    </div>

    <div class="bg-white border mt-2 py-2 px-4">
        <div class="row pt-3">
            <div class="col-4 d-flex p-0">
                <p class="mx-auto list-cat list-cat-active">All</p>
            </div>
            <div class="col-4 d-flex p-0">
                <p class="mx-auto list-cat">Fiction</p>
            </div>
            <div class="col-4 d-flex p-0">
                <p class="mx-auto list-cat">Non-Fiction</p>
            </div>
        </div>
        <div class="row pt-2">
            {% for novel in novels %}
            <div class="col-6 col-md-3 p-2 p-md-3 mb-1 list-novel list-novel-{{ novel.category }}">
                <div class="card border-0 mx-auto list-card" onclick="location.href='{% url 'series' novel.pk %}'">
                    <img src="{% with 'sosull/cover/'|add:novel.title|add:'.jpg' as image_static %}{% static image_static %}{% endwith %}" alt="{{ novel.title }}">
                    <div class="card-body px-2 px-md-3 bg-dark text-white py-2 d-flex justify-content-between">
                        <p class="mb-0 list-novel-title">{{ novel.title }}</p>
                        <p class="mb-0 list-novel-cat text-secondary">{{ novel.category }}</p>
                    </div>
                    <div class="card-footer p-0">
                        <div class="progress" style="height: 5px;">
                            {% for marker in novel.marker_set.all %}
                                {% if marker.user == request.user %}
                                    <div class="progress-bar bg-info" role="progressbar" style="width: {{ marker.percent }}%;" aria-valuenow="{{ marker.percent }}" aria-valuemin="0" aria-valuemax="100"></div>
                                {% else %}
                                    <div class="progress-bar bg-info" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<nav class="navbar navbar-light mt-2">
    <div class="container">
        <p class="logo text-secondary">SOSULLGA</p>
    </div>
</nav>

<script type="text/javascript">
$(document).on('click', '.list-cat', function(e){
    var $type = $(this).html();
    console.log($type);
    if($type == "All"){
        $('.list-novel').show();
    } else {
        $('.list-novel').hide();
        $('.list-novel-'+$type).show();
    }
})
</script>
{% endblock %}

sosull/templates/sosull/login.html
{% extends "sosull/base.html" %}
{% load static %}

{% block title %}
소설가 | 로그인
{% endblock %}

{% block body %}
<nav class="navbar navbar-light bg-white">
    <a class="navbar-brand" href="{% url 'index' %}">sosullga</a>
    <a class="account ml-auto my-3 my-md-4 mr-2 mr-md-4" href="{% url 'login' %}">로그인</a>
</nav>
<nav class="navbar navbar-light bg-white pb-0">
    <div class="container px-2">
        <div class="row w-100 m-0" style="cursor: pointer;">
            <div class="col-6 active-tab d-flex" onclick="location.href='{% url 'login' %}'">
                <p class="mx-auto">로그인</p>
            </div>
            <div class="col-6 d-flex" onclick="location.href='{% url 'register' %}'">
                <p class="mx-auto">회원가입</p>
            </div>
        </div>
    </div>
</nav>


<div class="container py-3 px-3">
    <div class="row">
        <div class="col-11 col-md-5 mx-auto bg-white px-4 px-md-5 py-5 text-center">
            <h1 class="logo">sosullga</h1>
            {% if message %}
            <p class="mt-3 text-danger">{{ message }}</p>
            {% endif %}
            <form action="{% url 'login' %}" class="mt-4 mb-3" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" name="username" class="form-control rounded-0" id="username"
                        placeholder="아이디" required>
                </div>
                <div class="form-group">
                    <input type="password" name="password" id="password" class="form-control rounded-0"
                        placeholder="비밀번호" required>
                </div>
                <button type="submit" value="Login" class="mt-3 btn btn-info rounded-0 btn-block btn-lg">로그인</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}